/** 
 * @description All the Error messages that needed to be sent to Admin or App
 * @type {Object}
*/
module.exports.ErrorMessage = Object.freeze({
    INVALID_TOKEN: 'Unauthorized user.',
    INTERNAL_ERROR: 'Internal Server Error.',
    INVALID_CREDENTIAL: 'Invalid credentials.',
    SOMETHING_WRONG: 'Something went wrong!',
    NO_TOKEN: 'Please provide token.',
    EMAIL_NOT_REGISTERED: 'Provided email is not registered.',
    NOT_REGISTERED: "Provided email/mobile number is not registered.",
    RESET_PASSWORD_EXPIRED: 'Your Token has expired.',
    WRONG_PASSWORD: 'Please enter valid password.',
    INVALID_MOBILE: 'This mobile number is not valid.',
    EMAIL_EXIST: 'This email already exists.',
    NOT_FOUND: 'Requested data not found.',
    USER_NOT_FOUND: 'This user does not exist.',
    VENDOR_NOT_FOUND: 'This vendor does not exist.',
    UPDATE_NOT: "Unexpected error during update, please try again.",
    MOBILE_EXIST: 'This mobile number already exists.',
    USERNAME_EXIST: 'This user name already exists.',
    USER_ID: 'A valid User Id is required.',
    BLOCKED_BY_ADMIN: 'You are not authorized, please contact Admin.',
    DELETED_BY_ADMIN: 'Your account is deleted, please contact Admin.',
    FIELD_REQUIRED: 'Fields are required.',
    OLD_PASSWORD: 'You have provided an incorrect old password.',
    INCORRECT_JWT: 'Invalid JWT token.',
    FORBIDDEN: 'There was an error in sending email.',
    INVALID_OTP: 'Invalid OTP',
    OTP_EXPIRED: "OTP has expired, please try resend OTP.",
    BRANCH_EXIST: "This branch name already exists.",
    INTEREST_EXIST: "This interest name already exists.",
    BUSINESS_CATEGORY_EXIST: "This business category name already exists.",
    CATEGORY_EXIST: "This category already exists.",
    SUBCATEGORY_EXIST: "This sub-category already exists.",
    ITEM_EXIST: "This sort item already exists.",
    BRAND_EXIST: "This brand name already exists.",
    DEPARTMENT_EXIST: "This department name already exists.",
    DESIGNATION_EXIST: "This designation already exists.",
    ROLE_EXIST: "This roll name is already exists",
    DOCUMENT_EXIST: "This document already exists",
    DOCUMENT_NAME_EXISTS: "This document name is already exists please any other document name",
    ROLE_EXIST: "This roll name is already exists.",
    DOCUMENT_EXIST: "This document already exists.",
    DOCUMENT_NAME_EXISTS: "This document name is already exists please any other document name.",
    PROMOTION_EXIST: "Promotion name already exists.",
    OFFER_NOT_FOUND: "Offer not found",
    PASSWORD_NOT_MATCHED: "Password not matched",
    TITLE_EXIST: "This title already exists.",




});

/** 
 * @description All the Success messages that needed to be sent to App or Admin
 * @type {Object}
*/
module.exports.SuccessMessage = Object.freeze({
    SIGNUP_SUCCESSFULLY: "Thanks, You have successfully signed up.",
    LOGIN_SUCCESS: 'Your login is successful.',
    FORGET_SUCCESS: 'A password link has been sent to your registered ID.',
    RESET_SUCCESS: 'Your password has been changed successfully.',
    LOGOUT_SUCCESS: "Logout successful.",
    PRODUCT_LIST_FETCH: 'Successfully fetched product list.',
    USER_LIST_FETCH: 'Successfully fetched user list.',
    AUTHORIZATION: 'This User is Authorized.',
    ACCOUNT_CREATION: 'Your account has been created successfully.',
    EMAIL_SEND: "Otp has been sent to your registered Email successfully.",
    OTP_SEND: 'Otp has been sent to your registered mobile number.',
    VERIFY_OTP: 'OTP verified successfully.',
    PIN_SET: "Your Pin has been set successfully.",
    PASSWORD_UPDATE: "Your password has been updated successfully.",
    DATA_SAVED: "Data is saved successfully.",
    DETAIL_GET: "Details have been fetched successfully.",
    DATA_FOUND: "Requested data found.",
    PROFILE_DETAILS: "Your profile detail has been updated sucessfully.",
    STATUS_UPDATED: "Your Status has been changed successfully.",
    UPDATE_SUCCESS: "Successfully updated.",
    BLOCK_SUCCESS: "Successfully blocked.",
    UNBLOCK_SUCCESS: "Successfully activated.",
    DELETE_SUCCESS: "Successfully deactivated.",
    CONSUMER_ADD: "Consumer has been added successfully.",
    VENDOR_ADD: "Vendor has been added successfully.",
    BRANCH_ADD: "Branch has been added successfully.",
    SUB_ADMIN_CREATED: "Sub-admin has been created successfully.",
    INTEREST_ADD: "Interest has been added successfully.",
    BUSINESS_CATEGORY_ADD: "Business category has been added successfully.",
    SORT_ITEM_ADD: "Sort item has been added successfully.",
    BRAND_ADD: "Brand has been added successfully.",
    CATEGORY_ADD: "Category has been added successfully.",
    SUBCATEGORY_ADD: "Sub-category has been added successfully.",
    DEPARTMENT_ADD: "Department has been added successfully.",
    DESIGNATION_ADD: "Designation has been added successfully.",
    SOCIAL_LINK_ADD: "Social link has been added successfully.",
    PROMOTION_ADD: "Promotion has been added successfully.",
    OFFER_ADD: "Offer has been added successfully.",
    CARD_ADD: "Card has been added successfully.",
    ALERT_ADD: "Item has been added to alert list successfully.",
    LOCATION_ADD: "Location added successfully.",
    NOTIFICATION_ADD: "Notification has been added successfully.",
    RESPOND_SUCCESS: "Responded successfully.",
    FAVOURITE_ADD: "Offer has been added to favourites list successfully.",
    FILTER_ADDED_SUCCESSFULLY:"filter added successfully.",
    REVIEW_ADDED:"review added successfully."
});